export enum TypeOfBaseLetter {
  COMMUNICATION_LETTER = "COMMUNICATION_LETTER",
  BUDGET_PROPOSAL_LETTER = "BUDGET_PROPOSAL_LETTER",
  IMPLEMENTATION_LETTER_IN_CAMPUS = "IMPLEMENTATION_LETTER_IN_CAMPUS",
  IMPLEMENTATION_LETTER_OFF_CAMPUS = "IMPLEMENTATION_LETTER_OFF_CAMPUS",
  PERMIT_TO_ENTER_LETTER = "PERMIT_TO_ENTER_LETTER",
  SCHOOL_FACILITY_LETTER = "SCHOOL_FACILITY_LETTER",
}
export interface BaseLetter {
  base_letter_request_body_type: TypeOfBaseLetter;
  type: TypeOfBaseLetter;
}
